# Generated by Django 6.0.5 on 2026-05-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('A', 'ADMIN'), ('D', 'DOCTOR'), ('P', 'PATIENT')], default=None, max_length=10),
        ),
    ]
