# Generated by Django 6.0.5 on 2026-05-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(),
        ),
    ]
