# Generated by Django 6.0.5 on 2026-05-28 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to='patients.patientprofile')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['patient'], name='patient_appointment_index'), models.Index(fields=['doctor', 'status'], name='appointment_doctor_status_idx'), models.Index(fields=['patient', 'status'], name='appointment_patient_status_idx'), models.Index(fields=['start_time'], name='appointment_start_time_index')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('doctor', 'start_time'), name='unique_doctor_appointment_time')],
            },
        ),
    ]
